{{- if and (gt (len .Values.files.data) 0) (not .Values.files.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baton-sql.filesSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "baton-sql.labels" . | nindent 4 }}
    app.kubernetes.io/component: files
type: Opaque
stringData:
  {{- toYaml .Values.files.data | nindent 2 }}
{{- end }}
