{{- if and .Values.secret.create (not .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baton-sql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "baton-sql.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  BATON_CLIENT_ID: {{ .Values.secret.clientId | quote }}
  BATON_CLIENT_SECRET: {{ .Values.secret.clientSecret | quote }}
  {{- range $k, $v := .Values.secret.extra }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
